/**
 * Openings Materials Seed Data
 * Doors, Windows and Hardware materials
 */

export const OPENINGS_MATERIALS_SEED_DATA = [
    // ===== DOORS =====
    {
        name: "Premium Teak Wood Main Door",
        category: "Openings",
        subCategory: "Doors",
        type: "Main Door (Teak)",
        grade: "Premium",
        dimensions: "3.5' x 7'",
        pricePerUnit: 45000,
        unit: "Nos (Numbers)",
        imageUrl: "https://images.unsplash.com/photo-1506377295352-e3154d43ea9e?w=400",
        availability: "In Stock",
        rating: 4.9,
        reviews: 45,
    },
    {
        name: "Solid Core Flush Door",
        category: "Openings",
        subCategory: "Doors",
        type: "Flush Door",
        grade: "Standard",
        dimensions: "3' x 7'",
        pricePerUnit: 6500,
        unit: "Nos (Numbers)",
        imageUrl: "https://images.unsplash.com/photo-1533282960533-51328aa49826?w=400",
        availability: "In Stock",
        rating: 4.5,
        reviews: 120,
    },
    {
        name: "Century WP Flush Door",
        category: "Openings",
        subCategory: "Doors",
        type: "Flush Door",
        grade: "Premium",
        dimensions: "3' x 7'",
        pricePerUnit: 8500,
        unit: "Nos (Numbers)",
        imageUrl: "https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=400",
        availability: "In Stock",
        rating: 4.7,
        reviews: 88,
    },
    {
        name: "Sintex PVC Bath Door",
        category: "Openings",
        subCategory: "Doors",
        type: "PVC/UPVC Door",
        grade: "Economy",
        dimensions: "2.5' x 6.5'",
        pricePerUnit: 3200,
        unit: "Nos (Numbers)",
        imageUrl: "https://images.unsplash.com/photo-1548586196-bb72b38b99ec?w=400",
        availability: "In Stock",
        rating: 4.2,
        reviews: 210,
    },

    // ===== WINDOWS =====
    {
        name: "Fenesta UPVC Sliding Window",
        category: "Openings",
        subCategory: "Windows",
        type: "UPVC Window",
        grade: "Premium",
        dimensions: "4' x 4'",
        pricePerUnit: 12500,
        unit: "Nos (Numbers)",
        imageUrl: "https://images.unsplash.com/photo-1510074377623-8cf13fb86c08?w=400",
        availability: "In Stock",
        rating: 4.8,
        reviews: 65,
    },
    {
        name: "Domal Aluminium Casement Window",
        category: "Openings",
        subCategory: "Windows",
        type: "Aluminium Window",
        grade: "Standard",
        dimensions: "3' x 4'",
        pricePerUnit: 8500,
        unit: "Nos (Numbers)",
        imageUrl: "https://images.unsplash.com/photo-1621259182978-f09e5e2ca08d?w=400",
        availability: "In Stock",
        rating: 4.6,
        reviews: 42,
    },
    {
        name: "Classic Country Wood Window",
        category: "Openings",
        subCategory: "Windows",
        type: "Timber Window",
        grade: "Standard",
        dimensions: "3' x 4'",
        pricePerUnit: 7500,
        unit: "Nos (Numbers)",
        imageUrl: "https://images.unsplash.com/photo-1587582423116-ec07293f0395?w=400",
        availability: "In Stock",
        rating: 4.4,
        reviews: 35,
    },
    {
        name: "MS Safety Grill Box Design",
        category: "Openings",
        subCategory: "Windows",
        type: "MS Safety Grill",
        grade: "Standard",
        dimensions: "12mm square bar",
        pricePerUnit: 85,
        unit: "Kg",
        imageUrl: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400",
        availability: "In Stock",
        rating: 4.3,
        reviews: 156,
    },

    // ===== HARDWARE =====
    {
        name: "Godrej Ultra Tribolt Lock",
        category: "Openings",
        subCategory: "Hardware",
        type: "Lock Set",
        grade: "Premium",
        pricePerUnit: 3450,
        unit: "Nos (Numbers)",
        imageUrl: "https://images.unsplash.com/photo-1510511459019-5dee99cc0f3b?w=400",
        availability: "In Stock",
        rating: 4.8,
        reviews: 532,
    },
    {
        name: "SS Ball Bearing Hinges 4-inch",
        category: "Openings",
        subCategory: "Hardware",
        type: "Hinges",
        grade: "SS 304",
        pricePerUnit: 320,
        unit: "Nos (Numbers)",
        imageUrl: "https://images.unsplash.com/photo-1510511459019-5dee99cc0f3b?w=400",
        availability: "In Stock",
        rating: 4.7,
        reviews: 245,
    }
];
