/**
 * Roofing Materials Seed Data
 * Complete roofing materials covering RCC Slab, Sloped Roof - Tile, and Sloped Roof - Sheet
 * Used for one-click admin seeding in DashboardScreen
 */

export const ROOFING_MATERIALS_SEED_DATA = [
  // ===== RCC SLAB MATERIALS =====
  {
    name: "Lafarge PPC Cement 50kg",
    category: "Roof",
    subCategory: "RCC Slab",
    type: "Cement",
    grade: "PPC",
    dimensions: "50kg Bag",
    pricePerUnit: 380,
    unit: "Bag (50kg)",
    imageUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400",
    availability: "In Stock",
    rating: 4.6,
    reviews: 412,
  },
  {
    name: "Ramco OPC Cement 50kg",
    category: "Roof",
    subCategory: "RCC Slab",
    type: "Cement",
    grade: "OPC",
    dimensions: "50kg Bag",
    pricePerUnit: 385,
    unit: "Bag (50kg)",
    imageUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400",
    availability: "In Stock",
    rating: 4.5,
    reviews: 356,
  },
  {
    name: "TATA Steel TMT Fe 550",
    category: "Roof",
    subCategory: "RCC Slab",
    type: "Steel (TMT Bar)",
    grade: "550MPa",
    dimensions: "8mm - 32mm",
    pricePerUnit: 56,
    unit: "Kg",
    imageUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400",
    availability: "In Stock",
    rating: 4.7,
    reviews: 523,
  },
  {
    name: "Vizag Steel TMT Fe 500",
    category: "Roof",
    subCategory: "RCC Slab",
    type: "Steel (TMT Bar)",
    grade: "500MPa",
    dimensions: "8mm - 32mm",
    pricePerUnit: 52,
    unit: "Kg",
    imageUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400",
    availability: "In Stock",
    rating: 4.5,
    reviews: 421,
  },
  {
    name: "River Sand (Washed)",
    category: "Roof",
    subCategory: "RCC Slab",
    type: "Sand",
    grade: "M Grade",
    dimensions: "As Required",
    pricePerUnit: 35,
    unit: "Cubic Feet (cft)",
    imageUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400",
    availability: "In Stock",
    rating: 4.4,
    reviews: 287,
  },
  {
    name: "Aggregate 20mm",
    category: "Roof",
    subCategory: "RCC Slab",
    type: "Aggregate",
    grade: "20mm",
    dimensions: "As Required",
    pricePerUnit: 42,
    unit: "Cubic Feet (cft)",
    imageUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400",
    availability: "In Stock",
    rating: 4.3,
    reviews: 256,
  },
  {
    name: "Aggregate 40mm",
    category: "Roof",
    subCategory: "RCC Slab",
    type: "Aggregate",
    grade: "40mm",
    dimensions: "As Required",
    pricePerUnit: 38,
    unit: "Cubic Feet (cft)",
    imageUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400",
    availability: "In Stock",
    rating: 4.2,
    reviews: 234,
  },

  // ===== SLOPED ROOF - TILE MATERIALS =====
  {
    name: "JSW Steel Truss Profile",
    category: "Roof",
    subCategory: "Sloped Roof - Tile",
    type: "Steel Truss",
    grade: "Grade A",
    dimensions: "As Designed",
    pricePerUnit: 75,
    unit: "Kg",
    imageUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400",
    availability: "In Stock",
    rating: 4.6,
    reviews: 325,
  },
  {
    name: "Premium Teak Wood Truss",
    category: "Roof",
    subCategory: "Sloped Roof - Tile",
    type: "Timber/Wood Truss",
    grade: "Premium Grade",
    dimensions: "4x4 to 6x8 inches",
    pricePerUnit: 380,
    unit: "Kg",
    imageUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400",
    availability: "In Stock",
    rating: 4.5,
    reviews: 276,
  },
  {
    name: "Clay Roof Tile - Mangalore",
    category: "Roof",
    subCategory: "Sloped Roof - Tile",
    type: "Clay Roof Tile",
    grade: "Standard",
    dimensions: "16x10 inches",
    pricePerUnit: 22,
    unit: "Nos (Numbers)",
    imageUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400",
    availability: "In Stock",
    rating: 4.4,
    reviews: 412,
  },
  {
    name: "Concrete Roof Tile - Interlocking",
    category: "Roof",
    subCategory: "Sloped Roof - Tile",
    type: "Concrete Roof Tile",
    grade: "Heavy Duty",
    dimensions: "20x12 inches",
    pricePerUnit: 28,
    unit: "Nos (Numbers)",
    imageUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400",
    availability: "In Stock",
    rating: 4.5,
    reviews: 356,
  },
  {
    name: "Natural Slate Tile",
    category: "Roof",
    subCategory: "Sloped Roof - Tile",
    type: "Slate Tile",
    grade: "Premium",
    dimensions: "24x14 inches",
    pricePerUnit: 85,
    unit: "Nos (Numbers)",
    imageUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400",
    availability: "In Stock",
    rating: 4.7,
    reviews: 234,
  },
  {
    name: "Waterproof Underlayment - 300gsm",
    category: "Roof",
    subCategory: "Sloped Roof - Tile",
    type: "Roofing Underlayment",
    grade: "300gsm",
    dimensions: "1m x 50m",
    pricePerUnit: 1200,
    unit: "Nos (Numbers)",
    imageUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400",
    availability: "In Stock",
    rating: 4.4,
    reviews: 189,
  },
  {
    name: "Waterproof Membrane - HDPE",
    category: "Roof",
    subCategory: "Sloped Roof - Tile",
    type: "Waterproof Membrane",
    grade: "HDPE 200 micron",
    dimensions: "1m x 50m",
    pricePerUnit: 1800,
    unit: "Nos (Numbers)",
    imageUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400",
    availability: "In Stock",
    rating: 4.5,
    reviews: 267,
  },

  // ===== SLOPED ROOF - SHEET MATERIALS =====
  {
    name: "Structural Steel Beam - Truss",
    category: "Roof",
    subCategory: "Sloped Roof - Sheet",
    type: "Steel Truss",
    grade: "Grade A",
    dimensions: "As Designed",
    pricePerUnit: 72,
    unit: "Kg",
    imageUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400",
    availability: "In Stock",
    rating: 4.6,
    reviews: 298,
  },
  {
    name: "Galvanized Iron Sheet - 0.45mm",
    category: "Roof",
    subCategory: "Sloped Roof - Sheet",
    type: "Galvanized Iron Sheet",
    grade: "GI 350",
    dimensions: "1m x 3m",
    pricePerUnit: 65,
    unit: "Kg",
    imageUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400",
    availability: "In Stock",
    rating: 4.5,
    reviews: 421,
  },
  {
    name: "Aluminium Sheet Roofing",
    category: "Roof",
    subCategory: "Sloped Roof - Sheet",
    type: "Aluminium Sheet",
    grade: "Grade A",
    dimensions: "1m x 3m",
    pricePerUnit: 185,
    unit: "Kg",
    imageUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400",
    availability: "In Stock",
    rating: 4.6,
    reviews: 356,
  },
  {
    name: "Polycarbonate Sheet - 6mm",
    category: "Roof",
    subCategory: "Sloped Roof - Sheet",
    type: "Polycarbonate Sheet",
    grade: "Clear",
    dimensions: "1m x 2m",
    pricePerUnit: 320,
    unit: "Nos (Numbers)",
    imageUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400",
    availability: "In Stock",
    rating: 4.4,
    reviews: 234,
  },
  {
    name: "Anti-condensation Felt - 250gsm",
    category: "Roof",
    subCategory: "Sloped Roof - Sheet",
    type: "Anti-condensation Felt",
    grade: "250gsm",
    dimensions: "1m x 50m",
    pricePerUnit: 950,
    unit: "Nos (Numbers)",
    imageUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400",
    availability: "In Stock",
    rating: 4.3,
    reviews: 178,
  },
  {
    name: "Waterproof Membrane - Bitumen",
    category: "Roof",
    subCategory: "Sloped Roof - Sheet",
    type: "Waterproof Membrane",
    grade: "APP Modified",
    dimensions: "1m x 50m",
    pricePerUnit: 2100,
    unit: "Nos (Numbers)",
    imageUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400",
    availability: "In Stock",
    rating: 4.5,
    reviews: 312,
  },
];
